package entities;

public enum CommandType {
    NO_COMMAND,
    VIEW_TOTAL_SALES,
    ORDER_SPECIFIC_INGREDIENT,
    VIEW_TOTAL_EXPENSES,
    VIEW_AVAILABLE_INGREDIENTS,
    VIEW_NET_PROFIT,
    PLACE_ORDER,
    EXIT,
    INPUT_INGREDIENT_QTY,
    ORDER_MULTIPLE_INGREDIENTS,
    FINALIZE_ORDER

}
